const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE";

const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
const DELETE_MESSAGE_FAILURE = "DELETE_MESSAGE_FAILURE";

const UPDATE_MESSAGE_REQUEST = "UPDATE_MESSAGE_REQUEST";
const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
const UPDATE_MESSAGE_FAILURE = "UPDATE_MESSAGE_FAILURE";

export default {
  UPDATE_MESSAGE_FAILURE,
  UPDATE_MESSAGE_SUCCESS,
  UPDATE_MESSAGE_REQUEST,
  DELETE_MESSAGE_FAILURE,
  GET_MESSAGES_REQUEST,
  GET_MESSAGES_SUCCESS,
  GET_MESSAGES_FAILURE,
  DELETE_MESSAGE_REQUEST,
  DELETE_MESSAGE_SUCCESS
};
